default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432
  username: 
  password:

development:
  <<: *default
  database: verve_db

test:
  <<: *default
  database: verve_db

production:
  <<: *default
  database: verve_db
